# Generated by Django 3.2.23 on 2023-11-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('tag_number', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=15)),
                ('area', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('local_assembly', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
